@startuml UseCase

' 1. Change the entire diagram background color
skinparam {
    BackgroundColor #F5F7FA
    DefaultFontColor #333333
}

left to right direction

actor "Customer" as User

rectangle "Blinkstay System" {
    ' top to bottom direction
    usecase "View Listings" as UC1
    usecase "View Listing Details" as UC2
    usecase "Book Room" as UC3
    usecase "Make Payment" as UC4
    usecase "View Booking" as UC5
    usecase "Cancel Booking" as UC6
    usecase "Write Review" as UC7
}

User --> UC1
' User --> UC2
User --> UC3
' User --> UC4
User --> UC5
User --> UC6
User --> UC7

UC1 --> UC2 : select listing
UC3 --> UC4 : require payment

@enduml

@startuml OverallDesign

left to right direction

actor "Customer" as customer
actor "Hotel Manager" as manager
actor "Admin" as admin

package "Blinkstay System" {
    usecase "View Listing" as UC_View
    usecase "Booking" as UC_Book
    usecase "Review" as UC_Review
    
    usecase "Manage Listing" as UC_ManageListing
    usecase "Manage Booking" as UC_ManageBooking
    usecase "Manage Reviews" as UC_ManageReviews
    
    usecase "Manage Users & Platform" as UC_AdminPlatform
}

' Customer Interactions
customer --> UC_View
customer --> UC_Book
customer --> UC_Review

' Hotel Manager Interactions
manager --> UC_ManageListing

' Admin Interactions
admin --> UC_AdminPlatform
admin --> UC_ManageListing
admin --> UC_ManageBooking
admin --> UC_ManageReviews

@enduml