spring.application.name=backend

# Server Configuration
server.port = 8080

# Load .env from local development
spring.config.import=optional:file:.env[.properties]

# Profile Configuration
spring.profiles.active=${SPRING_PROFILE}

# Local-Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Email Configurations
spring.mail.host=smtp.gmail.com
spring.main.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true