spring.application.name=backend

# Server Configuration
server.port=8080

# Load .env from local development
spring.config.import=optional:file:.env[.properties]

# Profile Configuration
spring.profiles.active=${SPRING_PROFILE}

# Local-Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Handling multipart files
# Maximum size allowed for a single uploaded file
spring.servlet.multipart.max-file-size=10MB
# Maximum total request size allowed for multipart/form-data
spring.servlet.multipart.max-request-size=10MB

# Email Configurations
spring.mail.host=${MAIL_HOST}
spring.main.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}

# JWT Configuration
# "your-super-secret-key-that-is-at-least-32-characters-long!"
jwt.signature=hgjfhtnchgdjhsdf;fj3434jsdfn[fdgjkret'fdgkjsdf[ewjgnd