# Cookie configuration

#For production, if your frontend and backend are on different sites, we may need:
#
#SameSite=None
#Secure=true

#whereas local development can generally use:
#
#SameSite=Lax
#Secure=false

app.cookie.secure=${COOKIE_SECURE:false}
app.cookie.same-site=${COOKIE_SAME_SITE:Lax}